import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
	title: "Chef",
	description: "Generated by Chef.js",
};

export default function RootLayout({ children }) {
	return (
		<html>
			<UserProvider>
				<body>{children}</body>
			</UserProvider>
		</html>
	);
}
