import Navbar from './navbar';
import Footer from './footer';
export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<>
		  <Navbar />
		  {children}
		  <Footer />
		</>
	);
}
