import Navbar from "./navbar";
export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<>
			<Navbar />
			{children}
		</>
	);
}
